### ISSUE TITLE
'Retained' on received message not indicated correctly

### ISSUE THREAD

**Issue by jckruege** [eclipse/paho.mqtt-spy#28]
If publish a message with 'retained' enabled, the GUI does not indicate the message is 'Retained'. The published message however does behave as a retained message, so it must be set correctly during publish from the GUI.

**Comment by TotallyInformation** [comment]
I see the same issue but not always. It seems to depend on how the subscription was formed. Possibly when using the "New" tab, the retained flag is not reflected correctly.

**Comment by kamilfb** [comment]
@jckruege @TotallyInformation - I will look into it. Thanks for raising this.

**Comment by kamilfb** [comment]
@jckruege @TotallyInformation - I had a look at what it does and also the MQTT 3.1.1 spec...

It seems to me mqtt-spy is working as expected. Please review this paragraph from the MQTT spec:

When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is sent as a result of a new subscription being made by a Client [MQTT-3.3.1-8]. It MUST set the RETAIN flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription regardless of how the flag was set in the message it received [MQTT-3.3.1-9].

What's your view?

**Comment by TotallyInformation** [comment]
Sorry for not responding. Happy to take your view - I'm certainly no MQTT expert. It is just that the behaviour is unexpected from a user perspective - perhaps some clarification in the docs would be helpful if you get a chance sometime?
