### ISSUE TITLE
Fail to create a new connection

### ISSUE THREAD

**Issue by tanchunwu** [eclipse/paho.mqtt-spy#32]
![image](https://user-images.githubusercontent.com/16300551/29961285-aca65350-8f31-11e7-92b7-85af451855c0.png)
environment: Windows 7, 32 bit operating system, J
operation: 
1. I use cmd windows to execute the  mqtt-spy-0.5.4-jar-with-dependencies.jar
2. Click second window to create a new connection, but there is no response
3. Click menu Connections=>Manage Connections, but there is no response.

And I attach the log.
[mqtt-spy.log.zip](https://github.com/eclipse/paho.mqtt-spy/files/1269640/mqtt-spy.log.zip)

**Comment by kamilfb** [comment]
Hi @tanchunwu , could you also include the version of Java you are running it with? Help -> About or java -version on the command line. See more info at https://github.com/eclipse/paho.mqtt-spy/wiki/GettingStarted

**Comment by kamilfb** [comment]
@tanchunwu Looks like the root cause of this is "java.lang.NoClassDefFoundError: javafx/scene/control/Dialog", which points to an old version of Java - could you confirm which one you are using?

**Comment by Jean-Rem** [comment]
Environment: Windows 10, 64 bit operating system,

java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
+ javafx-sdk-16

I use cmd windows to execute the mqtt-spy-1.0.1-beta-b18-jar-with-dependencies.jar
Click second window to create new connections, but there is no response
Click menu Connections=>Manage Connections, but there is no response.

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make com.sun.javafx.scene.text.TextLayout javafx.scene.text.TextFlow.getTextLayout() accessible: module javafx.graphics does not "opens javafx.scene.text" to unnamed module @2f01cc92

Could you help me for this problem?

Regards
